spec_version: "V1"
config:
  enable_pull_requests_from_forks: true
pipelines:
  /feature_.*/:
    triggers:
    - "COMMIT"
    stages:
    - name: "Code Validation stage"
      steps:
      - type: "JOB"
        name: "module-pdk-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "module-rspec-puppet"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: false
    - name: "Feature branch deployment"
      steps:
      - type: "DEPLOYMENT"
        name: "Deployment on cdpe-delivery"
        policy:
          name: "cd4pe_deployments::feature_branch"
        timeout: 3600000
        concurrent_compilations: 0
        all_deployments: false
        pe_server: "cdpe-delivery"
        target:
          type: "NODE_GROUP"
      auto_promote: false
  master:
    triggers:
    - "COMMIT"
    stages:
    - name: "Code Validation stage"
      steps:
      - type: "JOB"
        name: "module-pdk-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "module-rspec-puppet"
        concurrent_compilations: 0
        all_deployments: false
      - type: "PULL_REQUEST_GATE"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: all_succeeded
    - name: "Deployment to lower_uat"
      steps:
      - type: "DEPLOYMENT"
        name: "Deployment to lower_uat on cdpe-delivery"
        policy:
          name: "cd4pe_deployments::eventual_consistency"
        timeout: 3600000
        concurrent_compilations: 0
        all_deployments: false
        pe_server: "cdpe-delivery"
        target:
          type: "NODE_GROUP"
          node_group_id: "fcda068f-e499-44ef-81f2-255fc487b2e2"
      auto_promote: false
    - name: "Deployment stage to production"
      steps:
      - type: "DEPLOYMENT"
        name: "Deployment to production on cdpe-delivery"
        policy:
          name: "cd4pe_deployments::eventual_consistency"
        timeout: 3600000
        concurrent_compilations: 0
        all_deployments: false
        pe_server: "cdpe-delivery"
        target:
          type: "NODE_GROUP"
          node_group_id: "49169472-1d52-48ac-acd8-915187585730"
      auto_promote: false

