#!/bin/bash

for i in `env | grep ^DB`; do
  k=`echo $i | cut -d= -f1`
  v=`echo $i | cut -d= -f2`
  echo "env[$k] = $v;" >> /etc/php-fpm.d/www.conf
done

php-fpm&

/usr/sbin/nginx -c /etc/nginx/nginx.conf -g 'daemon off;'
